name: Open library docs CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.4

      # - uses: ammaraskar/sphinx-action@master
      #   with:
      #     docs-folder: "docs/"
      - uses: actions/setup-python@v2

      # - name: Set up Python
      #   uses: actions/setup-python@v2.2.1
      #   with:
      #     python-version: 3.9

      - name: Install dependencies
        run: |
          cd docs/
          pip install -r requirements.txt
      - name: Set permissions for docs directory
        run: chmod -R 777 docs


      - name: make the sphinx docs
        run: |
          make -C docs clean
          make -C docs html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: docs/_build/html
