name: Python CI Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        cd docs/
        pip install -r requirements.txt

    - name: make the sphinx docs
      run: |
        cd docs/
        make html

    # - name: Run Lighthouse CI
    #   uses: treosh/lighthouse-ci-action@v3
    #   with:
    #     configPath: "./lighthouserc.json"
    #     temporaryPublicStorage: true



    - name: Init new repo in dist folder and commit generated files
      run: |
        cd docs/_build/html/
        git init
        touch .nojekyll
        git add -A
        git config --global user.email "muhamzyali@gmail.com"
        git config --global user.name "Muhammed Ali"
        git commit -m 'deploy'
          git push --force origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    # - name: Force push to destination branch
    #   uses: ad-m/github-push-action@v0.5.0
    #   with:
    #     github_token: ${{ secrets.TOKEN }}
    #     branch: gh-pages
    #     force: true
    #     directory: ./docs/_build/html

    # - name: Force push to destination branch
    #   uses: actions/github-script@v5
    #   with:
    #     github-token: ${{ secrets.TOKEN }}
    #     script: |
    #       git config --global user.name "Muhammed Ali"
    #       git config --global user.email "muhamzyali@gmail.com"
    #       cd docs/_build/html/
    #       git init
    #       touch .nojekyll
    #       git add -A
    #       git commit -m 'Deploy'
    #       git push --force origin gh-pages
